### ISSUE TITLE
Calling setConfig after getFieldByName throws error

### ISSUE THREAD

**Issue by joaovpmamede** [StoutLogic/acf-builder#11]
```
Fatal error: Uncaught Error: Call to a member function setConfig() on array
```

This is because `getFieldByName` returns a `$field` which is an array.

**Comment by stevep** [comment]
You're right, hm. Initially I had getFieldByName protected and not part of the public API. It is used internally. This feature seems to be not fully baked to be in the public API. 

The expected behavior is that it would set some sort of internal cursor to that field, so it can be modified. Instead it just returns the field's config array. There isn't any internal cursor. All operations are done to the last field added (which is at the end of the internal fields array, using array_pop and array_push)

I'll have to think about this, but at the moment I'm leaning towards making it protected again for the time being, in favor of a better field modification API. I can see the need for modifyField functions and removeField functions. Something that more clearly describes the writer's intent, because I worry that  a bunch of getFieldByName functions being used everywhere might confuse to someone reading the code, and dilute the writers intention.

**Comment by stevep** [comment]
Close in favor or #12
