### ISSUE TITLE
Google map field missing

### ISSUE THREAD

**Issue by mindfullsilence** [StoutLogic/acf-builder#25]
No class method for google map field.

**Comment by stevep** [comment]
You're right. I didn't include it initially because it requires that an API key be setup and wasn't sure how to handle this dependency at first. But I did use one in a project recently, and I just ended up initializing the API Key like this:

I had to setup the API key like:
```php
add_action('acf/init', function() {
    acf_update_setting('google_api_key', 'YOUR_API_KEY');
}
```

Then when I added the field, I did it like this:
```php
$builder
    ->addField('map', 'google_map', [
        'zoom' => 17,
    ]);
```

Any type of field can be added using the `addField` method.

But we should have an `addGoogleMap` field, I agree. I will work on it, or if you need it sooner and don't want use the general `addField` method, it should be easy to implement yourself, just include a test for it in the [FieldsBuilderTest](https://github.com/StoutLogic/acf-builder/blob/master/tests/FieldsBuilderTest.php) file and submit a pull request.

[Here is more info](https://www.advancedcustomfiel…) in the ACF documentation on the google map field type.

**Comment by mindfullsilence** [comment]
Good that there's a built-in workaround. This project is pretty tight so I'll use that for now. Should have time afterward to get it worked out and submit PR.

Thanks man! This lib is great, btw.

**Comment by stevep** [comment]
Went ahead and created the function `addGoogleMap` and tests, ended up needing it today. Thanks for the kind words.
