### ISSUE TITLE
Php error on build

### ISSUE THREAD

**Issue by darisi** [StoutLogic/acf-builder#3]
Got a php error for the $banner->build() line. 

`Xdebug: Fatal error: Uncaught Error: Call to a member function build() on null `

Removing the function() wrapper solves the issue and the fields display properly. I used this line:

`add_action('acf/init', acf_add_local_field_group($banner->build()) );`

but i get 2 php notices for that new line:

`Undefined offset: 0`

Wonderful work btw, love the composer use, will try and get more into it in the following weeks. 👍

**Comment by stevep** [comment]
Thanks @darisi, can I ask what version of PHP you're using that generates these errors? Does running the test suite work for you? run `vendor/bin/phpunit` from the root dir. Thanks!

**Comment by stevep** [comment]
Ah I think I know why the fatal error happens, because `$banner` isn't passed into the closure with `use`. I still do think it needs to be wrapped in a closure or `acf_add_local_field_group` will execute instantly instead of being called by the `acf/init` action.

So try:
```
add_action('acf/init', function() use ($banner) {
   acf_add_local_field_group($banner->build());
});
```
Or create the $banner field inside the closure:
```
add_action('acf/init', function() {
    $banner = new StoutLogic\AcfBuilder\FieldsBuilder('banner');
    $banner
        ->addText('title')
        ->addWysiwyg('content')
        ->addImage('background_image')
        ->setLocation('post_type', '==', 'page')
            ->or('post_type', '==', 'post');
   acf_add_local_field_group($banner->build());
});
```

Also I currently don't test any actual WordPress integration, which is why the unit tests didn't catch it. 

I have yet to use this in production, I built it to use in a larger project I'm still developing based around [Timber](https://github.com/timber/timber), but wanted to release it separately because I think it can be useful on its own.

**Comment by darisi** [comment]
That seems to work with no php notices. I was using php 7 (inside Trellis vagrant box from Roots.io).

**Comment by stevep** [comment]
OK great, I'll fix the sample code in the README along with any references in the wiki. Thanks again.
