### ISSUE TITLE
Show Collapsed

### ISSUE THREAD

**Issue by christianmagill** [StoutLogic/acf-builder#30]
Since the collapsed setting for the repeater field uses the field key, which is often generated automatically, how about providing a method to set a field within a repeater as the item visible when collapsed.

```

$client
   ->addRepeater( 'contacts' )
      ->addText( 'first_name')
      ->addText( 'last_name')
      ->addText('nickname')
      ->addText('position')
         ->setAsCollapsedItem()
      ->endRepeater()
   ->setLocation( 'post_type', '==', 'client' );

```

**Comment by stevep** [comment]
I'm open to adding convenience methods like `instructions`, `defaultValue($value)`, or `required` though, those convenience methods currently act on the "current" field rather than its parent field. Collapse is an attribute on the repeater configuration.

Currently you can set it like:

```php
$client
   ->addRepeater( 'contacts' , [ 'collapsed' => 'position' ])
      ->addText('first_name')
      ->addText('last_name')
      ->addText('nickname')
      ->addText('position')
      ->endRepeater()
   ->setLocation( 'post_type', '==', 'client' );
```
or 
```php
$client
   ->addRepeater( 'contacts')
      ->setConfig('collapsed', 'position')
      ->addText('first_name')
      ->addText('last_name')
      ->addText('nickname')
      ->addText('position')
      ->endRepeater()
   ->setLocation( 'post_type', '==', 'client' );
```
If we created a `collapsed` convenience method on the `RepeaterBuilder` but it would need to take a field name as an argument.

Since `FieldBuilder` extends from `ParentDelegationBuilder`, any method call that doesn't exist on a field builder will propagate up to the ancestor chain until it finds a builder where the method exists. The only problem is that in this case it would expect the field name passed in as an argument, and the only way to do that would be to add the `collapsed` method to the `FieldBuilder` and I'm not sure if that is the right solution or not, I'd rather not pollute a classes with a bunch of methods that don't act upon that specific class.

Maybe the solution is to have the `ParentDelegationBuilder` pass a stack of instances it comes across up the chain and allow the receiving parent's method deal with it. Something like that, not sure. 

I will think about this more. Thanks for the idea!

**Comment by christianmagill** [comment]
Cool, my main concern reading the ACF documentation was that the actual "collapsed" key in the configuration array references the field key. In actuality wouldn't this be the group name and the field name combined in most instances? Or does the library handle this?

**Comment by stevep** [comment]
There is code that handles the name -> key conversion:
https://github.com/StoutLogic/acf-builder/blob/master/src/RepeaterBuilder.php#L73

Though looking at it I wonder if there is a bug, I'm not sure why the repeater is prepending its field name in front of it. 

In your code does this work?

```php
$client
   ->addRepeater( 'contacts' , [ 'collapsed' => 'position' ])
      ->addText('first_name')
      ->addText('last_name')
      ->addText('nickname')
      ->addText('position')
      ->endRepeater()
   ->setLocation( 'post_type', '==', 'client' );
```

**Comment by christianmagill** [comment]
Yes that code works as intended
