### ISSUE TITLE
addField documentation needs $type paramemter

### ISSUE THREAD

**Issue by christianmagill** [StoutLogic/acf-builder#34]
The type parameter is missing in the documentation:

https://github.com/StoutLogic/acf-builder/wiki/fields#fields

**Comment by stevep** [comment]
I see:
> The `type` setting is automatically generated based on the addField method used.

Is this what you're referring to?

**Comment by christianmagill** [comment]
`$builder->addField($name, $config = []);`

should be 

`$builder->addField($name, $type, $config = []);`

**Comment by christianmagill** [comment]
When addField is used generically

**Comment by stevep** [comment]
Oh perfect, thank you. There was so much wrong on that page.

**Comment by christianmagill** [comment]
Welcome. Much thanks on the library! I've been building a rather substantial set of forms and ACF Builder is making things a lot more manageable.

**Comment by stevep** [comment]
Awesome to hear. I think it is a tool a lot people could use. There does seem to be more ACF libraries popping up such as https://github.com/danielpost/acf-php which is used to define fields on the back end and https://github.com/samrap/acf-fluent which is used on the front end to get data the data out.

I haven't actively marketed ACF Builder in "fear" of having to support it :) but somehow people have found it and are using it, which is very exciting! So I think I'm interested in getting the word out now. Especially if others are willing to contribute with bug reports, helping shape the docs or even submitting pull requests, rather than just treating issues as a help desk.

I'm also interested to see how people are using it. It started as part of a larger project that I thought could be spun off and developed independently in its own package. And since I've not used it independently, I don't really get to see any issues or pain points that arise, such as #29

This is all severely off topic but would love to chat more. I have set up a gitter chat for this library if you'd like to talk more or if you did have questions. [![Join the chat at https://gitter.im/StoutLogic/acf-builder](https://badges.gitter.im/StoutLogic/acf-builder.svg)](https://gitter.im/StoutLogic/acf-builder?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
