### ISSUE TITLE
class Doctrine dependency issue when using without composer.

### ISSUE THREAD

**Issue by burning-brush** [StoutLogic/acf-builder#35]
When using the included autoload.php instead of composer, the repeaters and flexible fields fail when rewriting their 'Add Row' buttons.
I've tinkered with composer a little to try and properly set up the dependancies but I don't really know what I'm doing with it and don't have a lot of time to figure it out. It seems to download a lot of extra files that I don't need, particularly since this there are only two functions that rely on Doctrine. 
Do you happen to have a link where I can download a compiled version that solves this problem?

Otherwise I'm just going to have to comment out those class function calls which isn't necessarily ideal for version control. 

Aside from that this is a fantastic plugin, big improvement over working with the standard acf field arrays.

**Comment by stevep** [comment]
Yeah the Doctrine/Inflector is being used to pluralize the field name in the default add button label text  on repeaters and flexible content areas. If you pass in 'button_label' as an argument, getDefaultButtonLabel shouldn't get called. Though PHP still may complain because of the `use` statements in the classes.

You're right, after adding the dependency to composer, its hard use this library, standalone, without composer. The Doctrine/Inflector library is located here: https://github.com/doctrine/inflector You should probably be able to just require [this file](https://github.com/doctrine/inflector/blob/master/lib/Doctrine/Common/Inflector/Inflector.php) somewhere in your functions.php file.
