### ISSUE TITLE
ACF Group Field

### ISSUE THREAD

**Issue by christianmagill** [StoutLogic/acf-builder#40]
ACF now has a group field.

Would be great to see support added for it.

https://www.advancedcustomfields.com/resources/group/

**Comment by stevep** [comment]
Agreed. Also a **link** field. The link field will be easy to add, the group field I need to look into more. It seems very similar to the repeater though.

It is on my todo list for sure.

PS. The link field can be used currently by doing:
```php
$builder
    ->addField('field_name', 'link');
```

**Comment by Log1x** [comment]
Looking forward to the group field. 👍 

Thanks a lot for ACF Builder.

**Comment by stevep** [comment]
Just released version [v1.4.0](https://github.com/StoutLogic/acf-builder/releases/tag/v1.4.0)

New methods `addLink` and `addGroup`  A group is treated just like a repeater, but instead of an `endRepeater` function, there is an `endGroup` function. 

I'm releasing this before a refactor, which the code needs, because I wanted to get the functionality out there for everyone. I'm not happy with all of the inheritance, and I'm not longer happy with the confusing names `FieldsBuilder` vs `FieldBuilder` vs `GroupBuilder` Also I would like to use less magic methods if possible. Perhaps in a 2.0 release.

**Comment by kaisermann** [comment]
When trying to use the `addGroup` method, I'm getting a `Notice: Undefined index: _name in /..../plugins/advanced-custom-fields-pro/includes/fields/class-acf-field-group.php on line 254`. If switch to `addRepeater` (just for the sake of testing) it doesn't give me any error.

My code:

```php
$home_fields
    ->addImage('banner_image_id', [
        'label' => 'Imagem do banner',
        'wrapper' => [ 'width' => '50%' ],
        'return_format' => 'id',
    ])
    ->addGroup('honored_author', [
        'wrapper' => [ 'width' => '50%' ]
    ])
        ->addPostObject('id', [
            'label' => 'Autor Homenageado',
            'return_format' => 'id',
            'post_type' => 'author',
        ])
        ->addImage('image_id', [
            'label' => 'Imagem do autor homenageado',
            'return_format' => 'id',
        ])
    ->endGroup();

```

**Comment by stevep** [comment]
Thanks I will look into this

**Comment by Log1x** [comment]
I could be wrong, but I believe this was fixed on ACF's side with 5.6.1. I somewhat recall having this issue before updating.

**Comment by kaisermann** [comment]
Gonna check that out tomorrow, @Log1x!

**Comment by kaisermann** [comment]
Yep, updating to `5.6.2` has fixed the issue for me 🤔

**Comment by stevep** [comment]
Thanks @Log1x for figuring this out. Glad it was easy as an ACF update. I don't see anything specific about it in their change log but I haven't dived into the code.
