### ISSUE TITLE
Extention of FieldBuilder parent class

### ISSUE THREAD

**Issue by aprokopenko** [StoutLogic/acf-builder#64]
Hi Steve,

First of all, thanks for a cool extension for ACF.

We start using this extension a while ago and faced with a few problems.

1) We wrote a small class, which can register fields like this (If you like we can share this code. It allows re-use field definitions and modules definitions without any includes and keep code very clean):
http://prntscr.com/k1xqfy

* `$this->add()` just add it to internal $fields property, which then used to register fields through `acf_add_local_field_group()`
* `$this->builder()` just return an instance of Fields_Builder() class.

So you can add several fields group like: `$this->add( $this->builder('group1')->... , $this->builder('group2')->... )`

However in this way we stuck, that when we add fields we get wrong class instance at the end (we get FieldBuilder instance, not a FieldsBuilder). We wrote small `end()` method in our own child class. It looks like this:

```
	/**
	 * @return Fields_Builder
	 */
	public function end() {
		return $this->getParentContext() ? $this->getParentContext()->end() : $this;
	}
```

So it's very similar to endFlexibleContent() method. But it's global.

2) We use styling of fields to better organize edit interface on different screen resolution.
It's too much to write `setConfig('wrapper', ['some config'])` for each field, when all configs are similar. Code becomes to hard to read, because 70% of code goes to wrapper config array definitions. For each field class you have separate class and we can't overwrite FieldsBuilder to patch anything in the same way. 
We can make a pull request to your repository with method like setWrapper($width, $class, $id) inside parent FieldBuilder class (we are playing with the final syntax right now to make it easy to use/read). So we can call something like:

```
$this->builder('some group')
    ->addText('my_field')
        ->setWrapper('30%')
   ->addText('another_field)
       ->setWrapper('70%')
    ...
```

Are you interesting in such patches? We can deliver them to you this week.

**Comment by aprokopenko** [comment]
And one more suggestion: usually you need to set field group to some list of post types, without any complex conditions. 
We also added a method, which can simply create required syntax for setLocation. It take post names as an argument:

```
	/**
	 * @param string[] $post_types
	 * @return Fields_Builder
	 */
	public function attachPostTypes( $post_types ) {
		$post_types = (array) $post_types;

		$this->setLocation( 'post_type', '==', array_shift( $post_types ) );
		if ( ! empty( $post_types ) ) {
			foreach ( $post_types as $pt ) {
				$this->or( 'post_type', '==', $pt );
			}
		}

		return $this;
	}
```

**Comment by stevep** [comment]
Awesome to see other libraries building upon ACF Builder!  

You're right, FieldsBuilder::addField returns a FieldBuilder object instead of $this instance of the FieldsBuilder object. In the `ParnetDelegationBuilder` class, which both FieldsBuild and FieldBuilder extend from, there is a [`getRootContext`](https://github.com/StoutLogic/acf-builder/blob/master/src/ParentDelegationBuilder.php#L43-L53) function that will do exactly what your proposed `end` function does. Perhaps your `add` function can automatically call it when passed a builder. That way `getRootContext` or your proposed `end` function wouldn't need to be called manually by the user using your library. 

This would be my preferred way rather than adding an alias method for getRootContext.

Your second suggestion is something I do want to tackle, it gets used so much it definitely warrants a convenience method. Even more simply, I'd like a `setWidth` function directly on the FieldBuilder, by passing any mention of the wrapper. 

```php
$this->builder('some group')
    ->addText('my_field')
        ->setWidth('30%')
   ->addText('another_field')
        ->setWidth('70%')
    ...
```

The "wrapper" in ACF is also responsible for class names and id. I would accept a pull request if you wanted to tackle it before me. An internal wrapper config would need to be maintained, and this function would manipulate it.

Your third suggestion is something I also think is best left to libraries or users doing in their own functions.php file. ACF Builder provides the tools to implement it as you have. I'd rather only sparingly add convenience methods to individual fields (like setWidth) rather than the FieldsBuilder group as a whole, to keep the API down. 

I think you're implementation in your library is great. I also do something similar in my very undocumented [Understory / Understory ACF projects](https://github.com/StoutLogic/understory-acf/wiki).

An object (in this case a View, which just a wordpress template) is configured to have have a field group and the location is automatically set for the post type, taxonomy, user, template, etc.

```php
<?php

/**
 * Template Name: Home
 */

namespace StoutLogic\CustomTheme\Views;

use StoutLogic\CustomTheme\Fields\Banner;

class HomeTemplate extends \Understory\View;
{
    public function configure()
    {
        $this->has('banner', new Banner);
    }
}
```

In this example when the View is registered, the FieldGroup: Banner will have 
`->setLocation('page_template', '==', $viewFile);` called on its FieldsBuilder automatically, as well anywhere else Banner is used, perhaps a custom post type, and setLocation gets set appropriately.

**Comment by aprokopenko** [comment]
Hi again,

Thanks for a suggestion with getRootContext() - it works fine.

Regarding Wrapper attributes - I finally get a hands on some coding here. Wanted to confirm with you first - I suggest to add 2 methods:

`setWidth('% or px')`

and 

`setAttr($name, $value)`, which actually set wrapper config as $wrapper[$name] = $value. ACF has ability to add actually any attributes, not only class/id. So in this way we can be flexible and add anything in a clear way.

And I have one more idea on smart attr `$name` to use it like `->setAttr('.my-class')` to skip attribute name, because it's self-explanatory from CSS-selector syntax. What do you think about that?
